#pragma once

#define EXTENSIONSAMPLE_MAJORNUMBER          1
#define EXTENSIONSAMPLE_MINORNUMBER          0
#define EXTENSIONSAMPLE_BUILDNUMBER          0
#define EXTENSIONSAMPLE_MODIFICATIONNUMBER   0

#define TU_STR(value) #value
#define TU_STRINGIZE(value) TU_STR(value)

#define ExtensionSampleVersion EXTENSIONSAMPLE_MAJORNUMBER,EXTENSIONSAMPLE_MINORNUMBER,EXTENSIONSAMPLE_BUILDNUMBER,EXTENSIONSAMPLE_MODIFICATIONNUMBER
#define ExtensionSampleVersionStr TU_STRINGIZE(EXTENSIONSAMPLE_MAJORNUMBER.EXTENSIONSAMPLE_MINORNUMBER.EXTENSIONSAMPLE_BUILDNUMBER.EXTENSIONSAMPLE_MODIFICATIONNUMBER)
